### ISSUE TITLE
Broke in dmd 2.068.0

### ISSUE THREAD

**Issue by WebFreak001** [Dav1dde/gl3n#65] opened 2015-08-19 19:49 UTC
Every time I want to compile something with gl3n as dependency now it spams the console with
```dub\packages\gl3n-1.1.0\gl3n\linalg.d(425): Warning: int /= real is performing truncating conversion```
and then stops compilation.

Tested on windows (gl3n 1.0.1 and 1.1.0) and on linux (1.0.1)

**Comment by kiith-sa** [comment] 2015-08-23 15:38
Also happens to me (linux) - it seems DMD crashes? - the warnings may or may not be related to that.

From a verbose DMD log:

```
../../../../.dub/packages/gl3n-1.1.0/gl3n/linalg.d(425): Warning: int /= real is performing truncating conversion
../../../../.dub/packages/gl3n-1.1.0/gl3n/linalg.d(425): Warning: int /= real is performing truncating conversion
../../../../.dub/packages/gl3n-1.1.0/gl3n/linalg.d(425): Warning: int /= real is performing truncating conversion
../../../../.dub/packages/gl3n-1.1.0/gl3n/linalg.d(425): Warning: int /= real is performing truncating conversion
../../../../.dub/packages/gl3n-1.1.0/gl3n/linalg.d(425): Warning: int /= real is performing truncating conversion
../../../../.dub/packages/gl3n-1.1.0/gl3n/linalg.d(425): Warning: int /= real is performing truncating conversion
../../../../.dub/packages/gl3n-1.1.0/gl3n/linalg.d(425): Warning: int /= real is performing truncating conversion
../../../../.dub/packages/gl3n-1.1.0/gl3n/linalg.d(425): Warning: int /= real is performing truncating conversion
../../../../.dub/packages/gl3n-1.1.0/gl3n/linalg.d(425): Warning: int /= real is performing truncating conversion
semantic3 math
semantic3 plane
semantic3 util
```

**Comment by Dav1dde** [comment] 2015-08-23 16:27
Sorry I can't currently investigate this due to a broken PSU. But this wouldn't be the first DMD regression.

**Comment by ColdenCullen** [comment] 2015-08-26 05:33
It looks like this was fixed in 13f0c61816c86b656fca2bc217ba7d7762e04a21, can we get a new release with this commit please?

**Comment by Dav1dde** [comment] 2015-08-26 09:30
Created tag 1.2.0 and updated the dub repository. Please comment if it isn't fixed (works locally).

**Closed by Dav1dde** 2015-08-26 09:30 UTC
Labels: bug

**Comment by kiith-sa** [comment] 2015-08-29 14:59
Seems to work.
